
name = "ArmaForces Wargame"
mainprefix = "z"
prefix = "afwg"

[files]
include = [
    "LICENSE",
    "mod.cpp",
    "README.md",
    "armaforces_wargame_x64.dll",
]

exclude = ["*.psd", "*.png", "*.tga"]

[properties]
author = "ArmaForces"

[version]
path = "addons/main/script_version.hpp"
