PREP(createVehicleInfoForNonConfiguredVehicle);
PREP(currentHpString);
PREP(getAmmoInfo);
PREP(getGroupVehicles);
PREP(getVehicleDisplayName);
PREP(getVehicleInfo);
PREP(isEngineer);
PREP(isReconVehicle);
PREP(shouldStillBeVisible);
